# Generated by Django 4.2.30 on 2026-05-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='api_code',
            field=models.CharField(blank=True, default='', help_text='Open Food Facts code', max_length=50),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='api_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_carbs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_fiber',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_kcal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_salt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='nutrition_sugars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='serving_qty',
            field=models.PositiveIntegerField(default=100, help_text='Grams per serving'),
        ),
    ]
