# Generated by Django 4.2.30 on 2026-05-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_savedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('brands', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.URLField(blank=True, default='')),
                ('nutrition_kcal', models.FloatField(blank=True, default=0, null=True)),
                ('nutrition_fat', models.FloatField(blank=True, default=0, null=True)),
                ('nutrition_carbs', models.FloatField(blank=True, default=0, null=True)),
                ('nutrition_protein', models.FloatField(blank=True, default=0, null=True)),
                ('nutrition_fiber', models.FloatField(blank=True, default=0, null=True)),
                ('nutrition_salt', models.FloatField(blank=True, default=0, null=True)),
                ('nutrition_sugars', models.FloatField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
